import type {
  Anomaly,
  Budget,
  CloudAccount,
  CostRecord,
  OptimizationRecommendation,
  Service,
} from "./types.js";

export const accounts: CloudAccount[] = [
  {
    id: "acct_01",
    name: "Northstar Production",
    environment: "production",
    businessUnit: "Platform",
    ownerTeam: "Cloud Operations",
    monthlyBudget: 14000,
    region: "us-east-1",
  },
  {
    id: "acct_02",
    name: "Northstar Staging",
    environment: "staging",
    businessUnit: "Platform",
    ownerTeam: "Developer Experience",
    monthlyBudget: 4800,
    region: "us-east-1",
  },
  {
    id: "acct_03",
    name: "Atlas Analytics Production",
    environment: "production",
    businessUnit: "Data Products",
    ownerTeam: "Platform Engineering",
    monthlyBudget: 22000,
    region: "us-west-2",
  },
];

export const services: Service[] = [
  {
    id: "svc_01",
    accountId: "acct_01",
    name: "Kubernetes",
    category: "compute",
    environment: "production",
    monthlyCost: 18240,
    previousMonthlyCost: 12110,
    utilizationRate: 0.41,
    requestsPerThousand: 108,
  },
  {
    id: "svc_02",
    accountId: "acct_01",
    name: "Managed PostgreSQL",
    category: "database",
    environment: "production",
    monthlyCost: 6240,
    previousMonthlyCost: 5980,
    utilizationRate: 0.76,
    requestsPerThousand: 42,
  },
  {
    id: "svc_03",
    accountId: "acct_02",
    name: "Artifact Storage",
    category: "storage",
    environment: "staging",
    monthlyCost: 2150,
    previousMonthlyCost: 1780,
    utilizationRate: 0.59,
    requestsPerThousand: 24,
  },
  {
    id: "svc_04",
    accountId: "acct_03",
    name: "Warehouse Compute",
    category: "analytics",
    environment: "production",
    monthlyCost: 26400,
    previousMonthlyCost: 19820,
    utilizationRate: 0.48,
    requestsPerThousand: 86,
  },
];

export const costRecords: CostRecord[] = [
  {
    id: "cost_01",
    accountId: "acct_01",
    serviceId: "svc_01",
    month: "2026-05",
    monthlyCost: 18240,
    previousMonthlyCost: 12110,
    budget: 14000,
    environment: "production",
    businessUnit: "Platform",
    utilizationRate: 0.41,
    costPerCustomer: 18.2,
    costPerDeployment: 456,
    costPerThousandRequests: 108,
    tagged: true,
  },
  {
    id: "cost_02",
    accountId: "acct_01",
    serviceId: "svc_02",
    month: "2026-05",
    monthlyCost: 6240,
    previousMonthlyCost: 5980,
    budget: 7000,
    environment: "production",
    businessUnit: "Platform",
    utilizationRate: 0.76,
    costPerCustomer: 6.8,
    costPerDeployment: 156,
    costPerThousandRequests: 42,
    tagged: true,
  },
  {
    id: "cost_03",
    accountId: "acct_02",
    serviceId: "svc_03",
    month: "2026-05",
    monthlyCost: 2150,
    previousMonthlyCost: 1780,
    budget: 1900,
    environment: "staging",
    businessUnit: "Platform",
    utilizationRate: 0.59,
    costPerCustomer: 3.4,
    costPerDeployment: 97,
    costPerThousandRequests: 24,
    tagged: false,
  },
  {
    id: "cost_04",
    accountId: "acct_03",
    serviceId: "svc_04",
    month: "2026-05",
    monthlyCost: 26400,
    previousMonthlyCost: 19820,
    budget: 22000,
    environment: "production",
    businessUnit: "Data Products",
    utilizationRate: 0.48,
    costPerCustomer: 22.4,
    costPerDeployment: 622,
    costPerThousandRequests: 86,
    tagged: true,
  },
];

export const budgets: Budget[] = [
  {
    id: "budget_01",
    accountId: "acct_01",
    month: "2026-05",
    amount: 14000,
    forecast: 18850,
    owner: "Cloud Operations",
  },
  {
    id: "budget_02",
    accountId: "acct_02",
    month: "2026-05",
    amount: 4800,
    forecast: 4520,
    owner: "Developer Experience",
  },
  {
    id: "budget_03",
    accountId: "acct_03",
    month: "2026-05",
    amount: 22000,
    forecast: 26940,
    owner: "Platform Engineering",
  },
];

export const anomalies: Anomaly[] = [
  {
    id: "anom_01",
    costRecordId: "cost_01",
    type: "budget-variance",
    severity: "critical",
    summary: "Production Kubernetes spend is materially above budget and utilization is low.",
  },
  {
    id: "anom_02",
    costRecordId: "cost_03",
    type: "tagging-gap",
    severity: "high",
    summary: "Staging storage spend is missing full allocation tagging.",
  },
  {
    id: "anom_03",
    costRecordId: "cost_04",
    type: "month-over-month-growth",
    severity: "critical",
    summary: "Warehouse compute cost growth exceeds governance threshold.",
  },
];

export const recommendations: OptimizationRecommendation[] = [
  {
    id: "rec_01",
    serviceId: "svc_01",
    title: "Rightsize production Kubernetes node pools",
    priority: "critical",
    estimatedMonthlySavings: 4100,
    recommendedAction: "Review autoscaling baselines and reduce overprovisioned node capacity this sprint.",
  },
  {
    id: "rec_02",
    serviceId: "svc_03",
    title: "Enforce full staging allocation tags",
    priority: "high",
    estimatedMonthlySavings: 250,
    recommendedAction: "Apply mandatory business-unit and environment tags before the next monthly close.",
  },
  {
    id: "rec_03",
    serviceId: "svc_04",
    title: "Review reserved capacity strategy for analytics workloads",
    priority: "critical",
    estimatedMonthlySavings: 3600,
    recommendedAction: "Evaluate reserved pricing and workload scheduling to reduce warehouse cost volatility.",
  },
];
